import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { NextAuthProvider } from '@/components/providers/next-auth-provider';
import { ThemeProvider } from '@/components/providers/theme-provider';
import NavBar from '@/components/NavBar';
import { ShowSession } from '@/components/debug/ShowSession';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <NextAuthProvider>
      <html suppressHydrationWarning>
        <body className={`dark:bg-gray-900 dark:text-white font-sans ${inter.className}`}>
          <ThemeProvider
            attribute='class'
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <NavBar />
            {children}
            <ShowSession />
          </ThemeProvider>
        </body>
      </html>
    </NextAuthProvider>
  );
}
